// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 13.02.2026, 22:09:45
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/kacpe/OneDrive/Desktop/pink-facebook/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/kacpe/OneDrive/Desktop/pink-facebook/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/kacpe/OneDrive/Desktop/pink-facebook/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/kacpe/OneDrive/Desktop/pink-facebook/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/kacpe/OneDrive/Desktop/pink-facebook/plugins/**/*.{js,ts,mjs}","C:/Users/kacpe/OneDrive/Desktop/pink-facebook/composables/**/*.{js,ts,mjs}","C:/Users/kacpe/OneDrive/Desktop/pink-facebook/utils/**/*.{js,ts,mjs}","C:/Users/kacpe/OneDrive/Desktop/pink-facebook/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/kacpe/OneDrive/Desktop/pink-facebook/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/kacpe/OneDrive/Desktop/pink-facebook/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/kacpe/OneDrive/Desktop/pink-facebook/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;